<?php

namespace Vmj\VmjBundle\Repository;

/**
 * CategorieJobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieJobRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByImmersion($id) {
        $qb = $this->createQueryBuilder('c')
            ->Select('c')
            ->leftJoin('c.immersions', 'i')
            ->addSelect('i')
            ->Where('i.id = :id')
            ->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }
}
