<?php

namespace Vmj\VmjBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCommandesByImmersion($id){
        $qb = $this->createQueryBuilder('c')
            ->Select('c')
            ->Where('c.immersion = :id')
            ->setParameter('id', $id)
            ->andWhere('c.statut = 1');
        return $qb->getQuery()->getResult();
    }

    public function findImmersionsByProfessional($id){
        $qb = $this->createQueryBuilder('c')
            ->Select('i')->distinct()
            ->innerJoin('Vmj\VmjBundle\Entity\Formation', 'f', 'With', 'c.product = f.id')
            ->innerJoin('Vmj\VmjBundle\Entity\Immersion', 'i', 'With', 'f.immersion = i.id')
            ->innerJoin('Vmj\VmjBundle\Entity\Metier', 'm', 'With', 'i.metier = m.id')
            ->Where('m.professionnel = :id')
            ->setParameter('id', $id)
            ->andWhere('f.statut = 2')
            ->orderBy('i.id');
        return $qb->getQuery()->getResult();
    }

    public function findCommandesByProfessional($id){
        $qb = $this->createQueryBuilder('c')
            ->Select('i')->distinct()
            ->innerJoin('Vmj\VmjBundle\Entity\Formation', 'f', 'With', 'c.product = f.id')
            ->innerJoin('Vmj\VmjBundle\Entity\Immersion', 'i', 'With', 'f.immersion = i.id')
            ->innerJoin('Vmj\VmjBundle\Entity\Metier', 'm', 'With', 'i.metier = m.id')
            ->Where('m.professionnel = :id')
            ->setParameter('id', $id)
            ->andWhere('f.statut = 2')
            ->orderBy('i.id');
        return $qb->getQuery()->getResult();
    }

    /* Pour page statistiques */
    public function countAllCommandes()
    {
        return $this->createQueryBuilder('c')
        ->Select('COUNT(c)')
        ->getQuery()
        ->getSingleScalarResult();
    }
}
