<?php

namespace Vmj\VmjBundle\Repository;

/**
 * ConversationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationsRepository extends \Doctrine\ORM\EntityRepository {

    public function getTheConversation($expediteur, $destinataire) {
        $qb = $this->createQueryBuilder('u')
                ->Select('u')
                ->Where('u.emetteur = :emeteur or u.recepteur = :emeteur')
                ->andWhere('u.emetteur = :recepteur or u.recepteur = :recepteur')
                ->setParameter('emeteur', $expediteur)
                ->setParameter('recepteur', $destinataire)
                ->setMaxResults(1);
        return $qb->getQuery()->getResult();
    }
    
    public function getAdminConversation($expediteur) {
        $qb = $this->createQueryBuilder('u')
                ->Select('u')
                ->Where('u.emetteur = :emeteur or u.recepteur = :emeteur')
                ->andWhere('u.foradmin = 1')
                ->setParameter('emeteur', $expediteur)
                ->setMaxResults(1);
        return $qb->getQuery()->getResult();
    }

}
