<?php

namespace Vmj\VmjBundle\Repository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends \Doctrine\ORM\EntityRepository
{
    public function myParticuliersImmersions($idParticuliers){
        $qb = $this->createQueryBuilder('f')
                ->Select('f')
                ->Where('f.customer = :idParticuliers')
                ->setParameter('idParticuliers', $idParticuliers);
        return $qb->getQuery()->getResult();
    }

    public function findCommandesByImmersion($id){
        $qb = $this->createQueryBuilder('f')
            ->Select('f')
            ->Where('f.immersion = :id')
            ->setParameter('id', $id)
            ->andWhere('f.statut = 2');
        return $qb->getQuery()->getResult();
    }

    public function findFormationsByImmersion($id){
        $qb = $this->createQueryBuilder('f')
            ->Select('f')
            ->Where('f.immersion = :id')
            ->setParameter('id', $id);
            //->andWhere('f.statut = 1');
        return $qb->getQuery()->getResult();
    }
}
