<?php

namespace Vmj\VmjBundle\Repository;

/**
 * PresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenairesRepository extends \Doctrine\ORM\EntityRepository
{

}
