<?php

namespace Vmj\VmjBundle\Repository;

/**
 * PromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByName($name)
	{
		$qb = $this->createQueryBuilder('p')
            ->Select('p')
            ->Where('p.name = :name')
            ->andWhere('p.statut = 1')
            ->setParameter('name', $name);
        return $qb->getQuery()->getResult();
	}
}
