<?php

namespace Vmj\VmjBundle\Repository;

use Vmj\VmjBundle\Entity\Immersion;

/**
 * TemoignagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemoignagesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll(){
        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->innerJoin(Immersion::class, 'i', 'with', 't.immersion = i.id');
        return $qb->getQuery()->getResult();
    }
}
