hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@VmjUserBundle/Resources/config/routing/connect.xml"
    prefix:   /connect
    
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect

facebook_login:
    pattern: /connect/facebook

linkedin_login:
    pattern: /connect/linkedin


vmj_user:
    resource: "@VmjUserBundle/Resources/config/routing.yml"
    prefix:   /

vmj:
    resource: "@VmjBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
app:
    resource: @AppBundle/Controller/
    type:     annotation
